server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employees
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceURL:
      defaultZone: http://localhost:9001/eureka